### ISSUE TITLE
Not working on windows currently. 

### ISSUE THREAD

**Issue by leet0rz** [Exafunction/codeium.nvim#98]
After being able to finally launch it without problems (You need uuidgen in path on windows, you guys said we do not but we do.) the completion does not work. Saw some other people saying its nvim cmp not working with this. Is this being looked at?

**Comment by pqn** [comment]
We recently adopted this repo from the original author, so I'm still coming up to speed here. Happy to accept a contribution to change the docs regarding the uuidgen requirement, or migrate to using PowerShell for the generation. I'm not sure what you meant by "its nvim cmp not working with this" exactly, could you clarify?

**Comment by leet0rz** [comment]
> We recently adopted this repo from the original author, so I'm still coming up to speed here. Happy to accept a contribution to change the docs regarding the uuidgen requirement, or migrate to using PowerShell for the generation. I'm not sure what you meant by "its nvim cmp not working with this" exactly, could you clarify?

Some guy tracked down a cmp update that broke codeium. I think it is in one of the issues posted, it might be closed but I did find it back then when I made this post. I think I recall using an older version of cmp made it work again.

I fixed the issues that I had. in your docu it said uuidgen was not required to use codeium on windows, but it is as it does not work without it. So I downloaded it and added it to path, now codeium starst without errors but it does not work as mentioned by many other issues dating weeks back, just check the issue log.

Hoping this will work in the future for neovim 👍

**Comment by pqn** [comment]
From what I see, the uuidgen and nvim-cmp issues are resolved. Feel free to open a new issue if there's something else that's preventing issues.

**Comment by leet0rz** [comment]
> From what I see, the uuidgen and nvim-cmp issues are resolved. Feel free to open a new issue if there's something else that's preventing usage.

That is not the issue, the issue is that it is not working. I just stated that uuidgen  is needed for it to work even tho the documentation says otherwise so that is a false statement.

After walking through a minefield of errors (before I made this post), all errors are gone (also before I made this post), codeium still does not work like it does in vscode. There are plenty of issues with the exact same problem.

Reopen, this issue has not been solved.

**Comment by pqn** [comment]
Yes, uuidgen is a requirement, and I updated the documentation to remove the idea that it wasn't needed for Windows in https://github.com/Exafunction/codeium.nvim/pull/100.

We voluntarily adopted this extension so its users wouldn't be left stranded without their favorite way of using Codeium, so it would be helpful if you can be more specific in what issues you still need resolved.

**Comment by leet0rz** [comment]
> Yes, uuidgen is a requirement, and I updated the documentation to remove the idea that it wasn't needed for Windows in #100.
> 
> We voluntarily adopted this extension so its users wouldn't be left stranded without their favorite way of using Codeium, so it would be helpful if you can be more specific in what issues you still need resolved.

There is no auto completion, no errors. Like all the other issues. Some guy tracked it down to a new update from nvim-cmp, I already told you this in the thread.

**Comment by pqn** [comment]
The nvim-cmp error should be resolved by #84 and #88.

**Comment by leet0rz** [comment]
> The nvim-cmp error should be resolved by #84 and #88.
Unfortunately there is still no auto-completion working for this, I do have a lot of other plugins working with auto completion though. No errors, just says `Codeium.nvim: server updated` and no completion while typing. Auto-completion works with all my other plugins but not this one so I assume the problem with cmp is still there unless there is a new one. I don't know.

**Comment by schlich** [comment]
Can confirm that this is issue, and the multiple threads that were closed on the subject were less than helpful.

Please reopen this issue @pqn 

```
Error executing luv callback:
....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:274: post https://api.codeium.com/register_user/ - curl error exit_code=23 stderr={ "curl: (23) Failed writing received data to disk/application" }
stack traceback:
	[C]: in function 'error'
	....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:274: in function '_user_on_exit'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:240: in function '_shutdown'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:47: in function <.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:38>
E471: Argument required
E471: Argument required
Error executing luv callback:
....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:274: post https://api.codeium.com/register_user/ - curl error exit_code=23 stderr={ "curl: (23) Failed writing received data to disk/application" }
stack traceback:
	[C]: in function 'error'
	....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:274: in function '_user_on_exit'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:240: in function '_shutdown'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:47: in function <.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:38>
```
